In [ ]:
import numpy as np
import pandas as pd


from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from flask import Flask, render_template, request
import subprocess


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Training.csv to Training.csv


In [ ]:
df = pd.read_csv("Training.csv")

features = df.iloc[:, 0:132].values
labels = df.iloc[:, -1].values

print(features)

# print(features)

from sklearn.preprocessing import LabelEncoder

# encode string class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(labels)
label_encoded_y = label_encoder.transform(labels)

x_train, x_test, y_train, y_test = train_test_split(
    features, label_encoded_y, test_size=0.2, random_state=7
)

# print(y_train)

# print(y_train)

model = XGBClassifier()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

pred_labels = label_encoder.inverse_transform(y_pred)

# print(y_pred)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy: %.2f%%" % (accuracy * 100.0))

# print(x_test[0])

# print(pred_labels[0])

# print(y_test[0])

curans = model.predict([x_test[0]])



[[1 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 1 1]]
Accuracy: 100.00%


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving doctordatasetfinal.csv to doctordatasetfinal.csv


In [ ]:
df = pd.read_csv("doctordatasetfinal.csv")

In [ ]:
def get_doctor(ans):
  col_value0 = df.iloc[:,0].values.tolist()
  col_value1 = df.iloc[:,1].values.tolist()
  if ans in col_value1:
    position = col_value1.index(ans)
    return col_value0[position]

In [ ]:
def get_link(ans):
  col_value1 = df.iloc[:,1].values.tolist()
  col_value2 = df.iloc[:,2].values.tolist()
  if ans in col_value1:
    position = col_value1.index(ans)
    return col_value2[position]

In [ ]:
def get_google(ans):
  col_value1 = df.iloc[:,1].values.tolist()
  col_value3 = df.iloc[:,3].values.tolist()
  if ans in col_value1:
    position = col_value1.index(ans)
    return col_value3[position]

In [ ]:
def get_measure(ans):
  col_value1 = df.iloc[:,1].values.tolist()
  col_value4 = df.iloc[:,4].values.tolist()
  if ans in col_value1:
    position = col_value1.index(ans)
    col_value4[position]
    return col_value4[position]

Apply calamine lotion


In [ ]:
!pip install pyngrok --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 681.2/681.2 kB 11.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [ ]:
from pyngrok import ngrok
ngrok.kill()
NGROK_AUTH_TOKEN = "2MSbbMnJBIeXVuNgRizrAkg9f5x_FM9xJtr38C3aMzHKgqkP"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

In [ ]:
ngrok.connect(5000)

<NgrokTunnel: "https://d182-35-192-69-194.ngrok-free.app" -> "http://localhost:5000">

In [ ]:
from flask import Flask, render_template, request, jsonify
import json

app = Flask(__name__)
app.static_folder = "static"


@app.route("/")
def home():
    ans = " "
    return render_template("xgboost.html",ans=ans)

@app.route('/process_data', methods=['POST'])
def process_data():
    data = request.get_json()
    if data is None or not isinstance(data, list):
        return jsonify(error='Invalid input data'), 400

    # Validate and preprocess input data
    for value in data:
        if value not in (0, 1):
            return jsonify(error='Invalid input data'), 400
    data = np.array(data)

    # Make prediction
    curans = model.predict([data])
    ans = label_encoder.inverse_transform(curans)
    doctor = get_doctor(ans[0])
    link = get_link(ans[0])
    google = get_google(ans[0])
    measure = get_measure(ans[0])
    print(doctor)
    print(link)
    print(google)
    print(measure)
    # Return prediction as JSON response
    return jsonify(prediction=ans[0], doctor=doctor, link=link, google=google, measure=measure)


if __name__ == "__main__":
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 06:17:54] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 06:17:55] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 06:18:09] "POST /process_data HTTP/1.1" 200 -


Dr. Sukanya Mathupal
https://www.practo.com/chennai/doctor/dr-sukanya-mathupal-dermatologist?practice_id=1224581&specialization=Acne%20/%20pimples%20treatment&referrer=doctor_listing&category_name=service&category_id=144
https://goo.gl/maps/hfxYQnmGYbd7wLvL7
use a honey and cinnamon mask,spot treat with tea tree oil, moisturize with aloe vera, try brewer's yeast


INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 07:11:47] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 07:11:58] "POST /process_data HTTP/1.1" 200 -


None
None
None
None


INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 07:12:34] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 07:12:51] "POST /process_data HTTP/1.1" 200 -


Dr. M Ilayaraja
https://www.practo.com/vellore/doctor/drilayarajamani-gmail-com-homeopath?practice_id=844614&specialization=Allergy%20treatment&referrer=doctor_listing&category_name=service&category_id=193252
https://goo.gl/maps/unXNVUFpn2jy7phr5
Eat Saline nasal irrigation


INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 07:39:21] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [13/Apr/2023 07:40:03] "POST /process_data HTTP/1.1" 200 -


Dr. S. Arulprakash
https://www.practo.com/chennai/doctor/dr-s-arul-prakash?practice_id=1147147&specialization=Gastroenterologist&referrer=doctor_listing
https://goo.gl/maps/YtY9v6DP1Vmk6Lt58
Use extract of milk thistle plant


In [ ]:
!ngrok.kill()

/bin/bash: -c: line 1: syntax error: unexpected end of file
